### ISSUE TITLE
Ask for help

### ISSUE THREAD

**Issue by zsy9512** [gautamHCSCV/Transformers-Applications#1]
Sorry to bother you, but I noticed that you are the main contributor to the project "Modelling_Viscoelastic_Objects". I am very interested in this project and would like to ask you how I can get access to the datasets used in this project. Since there is no issue board for that project, I have no choice but to ask this question, so please forgive me for my rash behavior!
Perhaps you can provide an available contact for related work！
Thanks!

**Comment by gautamHCSCV** [comment]
You can have a look at the references of the following paper: https://ieeexplore.ieee.org/document/10224477

**Comment by gautamHCSCV** [comment]
Since you don't have any other comment, I am closing the issue.
